#!/bin/bash

curl 'https://api.github.com/users/kaosf/repos?per_page=100'        2> /dev/null | ruby -rjson -e 'JSON.parse(STDIN.read).each{|v|puts v["name"]}'
curl 'https://api.github.com/users/kaosf/repos?page=2&per_page=100' 2> /dev/null | ruby -rjson -e 'JSON.parse(STDIN.read).each{|v|puts v["name"]}'
