#!/usr/bin/env ruby

require 'net/http'
require 'json'

def get_sub_repositories(page = 1)
  JSON.parse(Net::HTTP.get(URI.parse(
    "https://api.github.com/users/kaosf/repos?page=#{page}&per_page=100"
  ))).map{ |v| v["name"] }
end

def print_repostories(repositories)
  repositories.each do |repository|
    puts repository
  end
end

rs = get_sub_repositories
print_repostories rs
page = 2
while rs.size >= 100
  rs = get_sub_repositories page
  print_repostories rs
  page += 1
end
